Inmotion unpacker len check
Wheellog/Wheellog.Android pull request #174
Opened 2021-04-17 05:08 UTC by palachzzz

unpacker refactor, len check included

2021-04-17 13:34 UTC, paymicro requested changes

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +        int len_ex = 0;
надо добавить комментарии за что отвечают эти лены

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +
много пустоты

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                    if (sz == 15) len_p = c & 0xFF;
одновременно эти два условия не выполняются. Пожтому лучше добавить
```suggestion
                    else if (sz == 15) len_p = c & 0xFF;
```

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +            state = UnpackerState.unknown;
а как же лены? 
```suggestion
            state = UnpackerState.unknown;
            int len_p = 0;
            int len_ex = 0;
```

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                    if ((c == (byte) 0x55 && oldc == (byte) 0x55) && ((sz == len_ex+21) || (len_p != 0xFE))) { // 18 header + 1 crc + 2 footer
Я сломал глаза... сложна...

2021-04-17 13:34 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                        buffer.write(0xAA);
может не писать в буффер начальные/конечные байты? Пусть вся проверка будет в unpacker-е

2021-04-17 15:33 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +            state = UnpackerState.unknown;
хорошее замечание

2021-04-17 15:37 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                    if ((c == (byte) 0x55 && oldc == (byte) 0x55) && ((sz == len_ex+21) || (len_p != 0xFE))) { // 18 header + 1 crc + 2 footer
Извиняй) На самом деле все просто, если это extended packet то проверяется чтобы длина соответствовала указанному в пакете (len_ex+21), а если это обычный пакет - то просто проверить на конец 55 55. Обычные пакеты это редкое явление - ответы на команды смены установок и алерты. Когда будет колесо и достаточно коротких пакетов, сделаю проверки длины и для обычного пакета.

2021-04-17 15:39 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                        buffer.write(0xAA);
Я как то давно об этом думал, но там все оффсеты поплывут, не хочу испытывать судьбу

2021-04-17 15:53 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                    if ((sz > len_ex+21) && (len_p == 0xFE)) reset(); // longer than expected
кстати после ресета наверно нужно добавить `return`
```suggestion
                    if ((sz > len_ex + 21) && (len_p == 0xFE)) { 
                        reset(); // longer than expected
                        return false;
                    }
```

2021-04-17 21:59 UTC, paymicro approved these changes
В принципе OK.
Завтра постараюсь потестить на колесе

2021-04-17 22:02 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                    if ((c == (byte) 0x55 && oldc == (byte) 0x55) && ((sz == len_ex+21) || (len_p != 0xFE))) { // 18 header + 1 crc + 2 footer
кстати в java в byte надо преобразовывать если число больше 0x7F. Тут и без этого норм должно быть

2021-04-18 11:52 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5; // after +1 and %10 = 0
это было бы норм для 9 (как в далеком оригинале)
но тут `5 + 1 = 6` и еще 4 шага
step 6 - мы тут
step 7 - 25ms
step 8 - 50ms
step 9 - 75ms
step 0 - 100ms and action!

2021-04-18 11:52 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                updateStep %= 10;
Всё таки так понятнее
```java
                if (updateStep > 10) {
                    updateStep = 0;
                }
```

2021-04-18 11:52 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5;
тут тоже следующее выполнение будет через 4 шага = 100мс

2021-04-18 12:31 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                updateStep %= 10;
зачем ифы плодить там, где их можно не плодить? Ну и как бы что непонятного в остатке от деления... )

2021-04-18 12:32 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5;
так и задумано, это ошибка случается тогда, когда BT модуль не смог отправить сообщение.

2021-04-18 12:38 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5; // after +1 and %10 = 0
в недалеком оригинале здесь стояло 35, но с учетом деления по модулю 10 - это равно тому что есть сейчас.
а в далеком оригинале здесь стояло 39, и в случае когда БТ модуль не мог отправить сообщение то они начинали сыпаться каждые 25мс бессмысленно засирая БТ сервис, который все равно не мог ничего отправить, поэтому была правка 39->35

2021-04-18 13:03 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5; // after +1 and %10 = 0
я про комментарий // after +1 and %10 = 0

2021-04-18 13:30 UTC, palachzzz commented on app/src/main/java/com/cooper/wheellog/utils/InMotionAdapter.java
> +                            updateStep = 5; // after +1 and %10 = 0
он видимо старый остался)

2021-04-19 03:41 UTC, merged