fix settings
Wheellog/Wheellog.Android pull request #6
Opened 2020-10-11 18:30 UTC by Sing303

Перенёс настройки 
 - фикс. процентов
 - напряжения подъёма педалей
 - ёмкости батки
 - мощности зарядника

В общие настройки, из настроек готвеев/ветеранов

2020-10-11 19:06 UTC, paymicro requested changes

2020-10-11 19:06 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/MainActivity.java
> +            correctedTiltbackVoltage = 79.2;
Я думаю, что логику с `gotwayVoltage` нужно перенести в адаптер

2020-10-11 19:42 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
> +            return 79.2;
может как-то так вместо трех условий?
```java
        min = 48 * (1 + (0.25 * mGotwayVoltageScaler);
        max = 52.8 * (1 + (0.25 * mGotwayVoltageScaler);
        if (tiltbackVoltage < min || tiltbackVoltage > max)
            return min;
```

2020-10-11 19:43 UTC, Sing303 commented on app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
> +            return 79.2;
Это гораздо сложнее воспринимается)
Лучше уж по проще

2020-10-11 19:45 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
> +            return 79.2;
ну не скажи. Так понятно хоть откуда эти числа растут.

2020-10-11 19:46 UTC, paymicro commented on app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
> +            return 79.2;
value * (1 + (0.25 * mGotwayVoltageScaler)) это можно в отдельный метод для упрощения, если его еще нет

2020-10-11 19:48 UTC, Sing303 commented on app/src/main/java/com/cooper/wheellog/utils/GotwayAdapter.java
> +            return 79.2;
Нужен Паша, мне такой короткий вариант не нравится ))

2020-10-12 18:55 UTC, palachzzz approved these changes

2020-10-12 18:58 UTC, merged